import { create } from 'zustand'
import type { Event } from './types'

const placeholderEvents: Event[] = [
  {
    id: "15000",
    title: "HYROX Bangkok 2025",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/15000.jpeg",
    description: "The ultimate fitness race combining running and functional workouts in Bangkok's premier venue.",
    bestOfImageUrl: "",
    location: "Bangkok, Thailand",
    time: "08:00",
    photographerIds: [],
  },
  {
    id: "13506",
    title: "Runaway Noosa Marathon & Swim Noosa 2025",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/13506.jpg",
    description: "Experience the stunning Noosa coastline in this iconic marathon and swimming event.",
    bestOfImageUrl: "",
    location: "Noosa, Australia",
    time: "06:30",
    photographerIds: [],
  },
  {
    id: "15540",
    title: "IRONMAN 70.3 Shanghai Chongming 2025",
    date: "2025-05-25",
    imageUrl: "https://www.sportograf.com/logos/15540.png",
    description: "Challenge yourself in the heart of China with this prestigious half-distance triathlon.",
    bestOfImageUrl: "",
    location: "Shanghai, China",
    time: "07:00",
    photographerIds: [],
  },
  {
    id: "13954",
    title: "IRONMAN 70.3 Kraichgau 2025",
    date: "2025-05-25",
    imageUrl: "https://www.sportograf.com/logos/13954.png",
    description: "Race through the beautiful German countryside in this challenging half-distance triathlon.",
    bestOfImageUrl: "",
    location: "Kraichgau, Germany",
    time: "07:30",
    photographerIds: [],
  },
  {
    id: "13960",
    title: "5150 Kraichgau 2025",
    date: "2025-05-25",
    imageUrl: "https://www.sportograf.com/logos/13960.jpg",
    description: "Perfect for beginners and seasoned athletes alike in the scenic Kraichgau region.",
    bestOfImageUrl: "",
    location: "Kraichgau, Germany",
    time: "09:00",
    photographerIds: [],
  },
  {
    id: "14187",
    title: "IRONMAN 70.3 Desaru Coast 2025",
    date: "2025-05-25",
    imageUrl: "https://www.sportograf.com/logos/14187.png",
    description: "Tropical paradise meets athletic excellence at Malaysia's premier triathlon destination.",
    bestOfImageUrl: "",
    location: "Desaru Coast, Malaysia",
    time: "07:00",
    photographerIds: [],
  },
  {
    id: "14220",
    title: "5150 Desaru Coast 2025",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/14220.jpg",
    description: "Sprint distance triathlon in the stunning tropical setting of Desaru Coast.",
    bestOfImageUrl: "",
    location: "Desaru Coast, Malaysia",
    time: "08:30",
    photographerIds: [],
  },
  {
    id: "13791",
    title: "Desaru Coast Sprint Triathlon 2025",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/13791.png",
    description: "Fast-paced sprint triathlon perfect for newcomers to the sport.",
    bestOfImageUrl: "",
    location: "Desaru Coast, Malaysia",
    time: "10:00",
    photographerIds: [],
  },
  {
    id: "13588",
    title: "XLETIX Challenge BERLIN 2025 presented by MaxiNutrition",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/13588.png",
    description: "Ultimate obstacle race challenge in Germany's capital city.",
    bestOfImageUrl: "",
    location: "Berlin, Germany",
    time: "09:00",
    photographerIds: [],
  },
  {
    id: "14010",
    title: "schauinsland Muddy Angel Run OFFENBACH 2025",
    date: "2025-05-24",
    imageUrl: "https://www.sportograf.com/logos/14010.gif",
    description: "Women-only obstacle run supporting charity causes.",
    bestOfImageUrl: "",
    location: "Offenbach, Germany",
    time: "11:00",
    photographerIds: [],
  },
  {
    id: "14188",
    title: "XLETIX Kids OFFENBACH 2025",
    date: "2025-05-25",
    imageUrl: "https://www.sportograf.com/logos/14188.jpg",
    description: "Fun obstacle course designed specifically for young athletes.",
    bestOfImageUrl: "",
    location: "Offenbach, Germany",
    time: "14:00",
    photographerIds: [],
  },
  {
    id: "13969",
    title: "Mountain Ultra-Trail by UTMB 2025",
    date: "2025-05-23",
    imageUrl: "https://www.sportograf.com/logos/13969.png",
    description: "Epic mountain trail running experience in breathtaking alpine terrain.",
    bestOfImageUrl: "",
    location: "Mountain, USA",
    time: "05:00",
    photographerIds: [],
  },
]

interface EventStore {
  events: Event[]
  selectedEvent: Event | null
  setSelectedEvent: (event: Event | null) => void
  getEventById: (id: string) => Event | undefined
}

export const useEventStore = create<EventStore>((set, get) => ({
  events: placeholderEvents,
  selectedEvent: null,
  setSelectedEvent: (event) => set({ selectedEvent: event }),
  getEventById: (id) => get().events.find(event => event.id === id),
})) 